### ISSUE TITLE
Using the issues page to assign tasks

### ISSUE THREAD

**Issue by mi3ll** [bradjerkson/betanarratives#1]
Hey @bradjerkson,

We can use this issues thing to assign tasks, make note of frameworks to use etc.

I think for the first prototype we are currently making, we should make a rule to only use one specific framework/template (so easier to integrate the two later, and they will look similar), and then we can make it pretty/more unique after we combine the two.

Are you happy with using Twitter Bootstrap + LESS for now? Or should we stick with the mediator theme + SASS? Or Twitter Bootstrap + SASS? (I have to learn SASS.... -.-)

**Comment by bradjerkson** [comment]
Hi Mel!
Sure, let's switch to Bootstrap + LESS.

**Comment by bradjerkson** [comment]
I will be designing the article separate from the website template for now

**Comment by bradjerkson** [comment]
Hey Mel!
I unfortunately didn't get the chance to overhaul the website into Bootstrap/LESS before the site launch today. It's still running on SASS. Is it at all possible for the Skin Deep article to use a separate framework?
